#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude node_modules \
	--exclude '*.log' \
	--exclude 'assets/data.ndjson' \
	. 'enceladus:~/doku-karte/'

ssh enceladus "\
cd ~/doku-karte
npm i
npm update
./update
forever stop doku-karte
export NODE_ENV=production
forever start -a --uid doku-karte index.js &"
